- name: my docker playbook
  hosts: webserver
  become: yes
  tasks:
    - name: docker installation
      apt:
        update_cache: yes
        name: docker.io
        state: present
    - name: starting enabling docker
      service:
        name: docker
        state: started
        enabled: yes
